### ISSUE TITLE
Command options not generating when added to report

### ISSUE THREAD

**Issue by IanJiang1** [vnijs/radiant#53] opened 2019-02-04 23:14 UTC

**Comment by IanJiang1** [comment] 2019-02-04 23:18
I am using ubuntu with os version 4.13.0-38-generic. I installed Radiant directly from the site following instructions. Whenever I add to Rmd report, the command does not have the associated option set, for instance, when predicting results from a linear model OLS > Predict and predict From command, the command 

pred <- predict(result, "Price=7.50")

is added, which returns an error. This is only fixed when I specify the argument keyword pred_cmd:

pred <- predict(result, pred_cmd ="Price=7.50")

All functions that are added to the report suffer from this deficiency. Any insights?

**Comment by vnijs** [comment] 2019-02-05 00:01
Thanks for reporting @IanJiang1 but I cannot reproduce the issue you are seeing. What exactly do you mean by "directly from the site"? Did you install from GitHub, from CRAN, or did you use the commands below:

```
install.packages("radiant.update", repos = "https://radiant-rstats.github.io/minicran/")
radiant.update::radiant.update()
```

Please provide the result from `sessionInfo()` and report on any changes after using the commands above.

If you are using ubuntu you might also be interested in using the dockers image I use with my students which has R, Rstudio, Radiant, Python, and JupyterLab. See install instructions below.

https://github.com/radiant-rstats/docker/blob/master/install/rsm-msba-linux.md

**Comment by vnijs** [comment] 2019-02-13 20:39
@IanJiang1 Was the issue resolved after the update? Any additional information you can provide would be useful

**Comment by vnijs** [comment] 2019-07-20 01:35
Closing. Please report any issues through https://github.com/radiant-rstats/radiant

**Closed as completed by vnijs** 2019-07-20 01:35 UTC
